### ISSUE TITLE
V2: Ideas and Umbrella ☂ 

### ISSUE THREAD

**Issue by yogeshkotadiya** [TryGhost/gatsby-plugin-advanced-sitemap#146]
Now that Gatsby 3 has been released, We should also proceed with the Next Major release.

Here are some of the changes that I'm proposing.

## Major Breaking Changes
- [ ] Drop Node 10 (EOL April 2021)
	- [ ] Remove deprecated API 	
- [ ] Upgrade to Gatsby 3
- [ ] Typescript?

## Features

- [ ] Support for `changefreq` and `priority` in XML
- [ ] Allows custom output path for individual sitemap

We can track the progress here.

**Comment by mrkaluzny** [comment]
@yogeshkotadiya  The plugin seems to be working with Gatsby 3 as expected, are there any major changes that have to happen? (I'm using this plugin in all projects :) )

**Comment by generalpiston** [comment]
Legitimately fix https://github.com/TryGhost/gatsby-plugin-advanced-sitemap/issues/13 ?

**Comment by aileen** [comment]
Apologies, I jumped the gun here! I didn't see this feature map and just released 2.0 with the Gatsby update. Feel free to keep adding features. Sorry 🙏

**Comment by tbaustin** [comment]
https://github.com/TryGhost/gatsby-plugin-advanced-sitemap/issues/16#issuecomment-865301474

**Comment by FelDev** [comment]
I'd love to have the feature of adding `hreflang` and `rel="alternate"` 
See issue #68
It's already a feature of gatsby-plugin-sitemap, so maybe inspiration can be drawn from there.
